"use client"

import { UserProvider } from '../contexts/authContext'
import './globals.css'
import { StrictMode } from 'react'
import ToastMessage from '../components/ToastMessage'
import { ChatProvider } from '@/contexts/chatContext'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StrictMode>
      <html lang="en">
        <body>
          <UserProvider>
            <ChatProvider>
              <ToastMessage />
              {children}
            </ChatProvider>
          </UserProvider>
        </body>
      </html>
    </StrictMode>
  )
}
